name: hoge ci
on: push

jobs:
  build:
   name: hoge
   runs-on: ubuntu-latest
   env:
    USER_NAME : "hoge"
   steps:
    # - run : mkdir build
    - run : ls
    - run : pwd
    - run : echo "hoge workd!"
    - name: Push to server
      uses: seijikojima/github_actions_tutorial@master
      with :
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: cd ${{ secrets.PROJECT_PATH }} && git pull
